
lint.ignore = [
    "CPY001", # Ignore licence header
    "PYI021", # Literally against the purpose of this plugin
]
lint.select = ["ALL"]
preview = true
[format]
    docstring-code-format = true
    preview               = true
[lint.pydocstyle]
    convention = "google"
[lint.per-file-ignores]
    "src/pql/sql/_code_gen/*.py" = [
        "A002",
        "ANN401",
        "FBT001",
        "FBT002",
        "PLR0913",
        "PLW1641",
    ]
    "t.py" = ["ANN201", "D100", "D101", "D103"]
    "tests/*" = [
        "D100",
        "D101",
        "D102",
        "D103",
        "D104",
        "DTZ001",
        "FBT001",
        "S101",
    ]
[lint.isort]
    combine-as-imports = true
